// 献立アプリ用レシピデータ
// category: "main"(主菜) / "side"(副菜) / "soup"(汁物)
// genre: "和" / "洋" / "中"
// protein: mainのみ。"鶏" / "豚" / "牛" / "魚" / "卵・豆腐"
// ingredients: 主な食材(調味料は基本のもののみ記載、塩コショウ等は省略可)
// time: 調理時間の目安(分)
// memo: ひとことポイント

const RECIPES = [

// ==================== 主菜(main) 約100品 ====================

// --- 鶏 (25品) ---
{ name: "鶏むね肉の照り焼き", category: "main", genre: "和", protein: "鶏",
  ingredients: ["鶏むね肉", "しょうゆ", "みりん", "砂糖", "酒"], time: 15,
  memo: "フライパンひとつ。甘辛だれでご飯がすすむ" },
{ name: "鶏もも肉のから揚げ", category: "main", genre: "和", protein: "鶏",
  ingredients: ["鶏もも肉", "しょうゆ", "しょうが", "にんにく", "片栗粉"], time: 25,
  memo: "下味は袋に入れてもむだけ。カリッと揚げる" },
{ name: "親子丼", category: "main", genre: "和", protein: "鶏",
  ingredients: ["鶏もも肉", "たまねぎ", "卵", "だし", "しょうゆ", "みりん"], time: 20,
  memo: "丼一杯で満足感◎。だしつゆで煮るだけ" },
{ name: "チキン南蛮", category: "main", genre: "和", protein: "鶏",
  ingredients: ["鶏もも肉", "卵", "片栗粉", "酢", "しょうゆ", "砂糖"], time: 25,
  memo: "甘酢だれとタルタルでご馳走感アップ" },
{ name: "鶏むね肉の油淋鶏", category: "main", genre: "中", protein: "鶏",
  ingredients: ["鶏むね肉", "片栗粉", "しょうゆ", "酢", "ねぎ", "しょうが"], time: 20,
  memo: "揚げ焼きで手軽に。ねぎだれが決め手" },
{ name: "よだれ鶏", category: "main", genre: "中", protein: "鶏",
  ingredients: ["鶏むね肉", "長ねぎ", "しょうゆ", "ラー油", "酢"], time: 20,
  memo: "茹でて切って和えるだけの簡単本格中華" },
{ name: "鶏肉と大葉のガーリック炒め", category: "main", genre: "和", protein: "鶏",
  ingredients: ["鶏もも肉", "大葉", "にんにく", "しょうゆ", "酒"], time: 15,
  memo: "香りよく食欲がすすむ一品" },
{ name: "手羽先のグリル", category: "main", genre: "洋", protein: "鶏",
  ingredients: ["手羽先", "塩", "こしょう", "オリーブオイル", "レモン"], time: 25,
  memo: "オーブンやグリルにおまかせで手間なし" },
{ name: "鶏肉のトマト煮", category: "main", genre: "洋", protein: "鶏",
  ingredients: ["鶏もも肉", "トマト缶", "たまねぎ", "にんにく", "コンソメ"], time: 25,
  memo: "煮込むだけでちゃんとした洋風おかずに" },
{ name: "鶏むね肉のチーズピカタ", category: "main", genre: "洋", protein: "鶏",
  ingredients: ["鶏むね肉", "卵", "粉チーズ", "小麦粉"], time: 15,
  memo: "衣に卵とチーズでしっとり柔らか" },
{ name: "鶏肉と野菜のクリーム煮", category: "main", genre: "洋", protein: "鶏",
  ingredients: ["鶏もも肉", "牛乳", "たまねぎ", "にんじん", "コンソメ"], time: 25,
  memo: "とろとろクリームで冬にうれしい一品" },
{ name: "バンバンジー風鶏むね肉", category: "main", genre: "中", protein: "鶏",
  ingredients: ["鶏むね肉", "きゅうり", "ごまだれ", "しょうゆ"], time: 20,
  memo: "レンジ蒸しでヘルシー。ごまだれが濃厚" },
{ name: "鶏の甘酢あん", category: "main", genre: "中", protein: "鶏",
  ingredients: ["鶏もも肉", "片栗粉", "酢", "砂糖", "しょうゆ", "ケチャップ"], time: 20,
  memo: "酢豚風の甘酢だれで鶏肉をさっぱりと" },
{ name: "鶏肉のみぞれ煮", category: "main", genre: "和", protein: "鶏",
  ingredients: ["鶏もも肉", "大根おろし", "だし", "しょうゆ", "みりん"], time: 15,
  memo: "大根おろしでさっぱり、消化にもやさしい" },
{ name: "鶏肉のねぎ塩だれ", category: "main", genre: "中", protein: "鶏",
  ingredients: ["鶏もも肉", "長ねぎ", "ごま油", "塩", "レモン汁"], time: 15,
  memo: "焼くだけ+ねぎ塩だれで箸が止まらない" },
{ name: "鶏むね肉のさっぱり梅蒸し", category: "main", genre: "和", protein: "鶏",
  ingredients: ["鶏むね肉", "梅干し", "大葉", "酒"], time: 15,
  memo: "レンジで簡単。夏場にもさっぱり食べられる" },
{ name: "鶏肉とキャベツの味噌炒め", category: "main", genre: "和", protein: "鶏",
  ingredients: ["鶏もも肉", "キャベツ", "味噌", "みりん", "にんにく"], time: 15,
  memo: "野菜もたっぷり摂れる満足系炒め物" },
{ name: "鶏肉の甘辛煮", category: "main", genre: "和", protein: "鶏",
  ingredients: ["鶏もも肉", "しょうゆ", "みりん", "砂糖", "しょうが"], time: 20,
  memo: "煮るだけで冷めても美味しい常備菜にも" },
{ name: "鶏むね肉のタンドリーチキン風", category: "main", genre: "洋", protein: "鶏",
  ingredients: ["鶏むね肉", "ヨーグルト", "カレー粉", "にんにく"], time: 20,
  memo: "漬け込んで焼くだけ。冷めても美味しい" },
{ name: "鶏肉と長芋の照り煮", category: "main", genre: "和", protein: "鶏",
  ingredients: ["鶏もも肉", "長芋", "しょうゆ", "みりん", "砂糖"], time: 20,
  memo: "ほくほく長芋と鶏肉の甘辛コンビ" },
{ name: "よだれ鶏風レンジ蒸し鶏サラダ", category: "main", genre: "中", protein: "鶏",
  ingredients: ["鶏むね肉", "レタス", "トマト", "ラー油だれ"], time: 15,
  memo: "レンジ蒸し鶏を野菜にのせるだけ" },
{ name: "鶏肉とピーマンの黒酢炒め", category: "main", genre: "中", protein: "鶏",
  ingredients: ["鶏もも肉", "ピーマン", "黒酢", "しょうゆ", "砂糖"], time: 15,
  memo: "コクのある黒酢だれでご飯がすすむ" },
{ name: "鶏むね肉のハーブソテー", category: "main", genre: "洋", protein: "鶏",
  ingredients: ["鶏むね肉", "オリーブオイル", "にんにく", "乾燥ハーブ"], time: 15,
  memo: "シンプルなソテーにハーブで風味アップ" },
{ name: "鶏肉と厚揚げの煮物", category: "main", genre: "和", protein: "鶏",
  ingredients: ["鶏もも肉", "厚揚げ", "しょうゆ", "みりん", "だし"], time: 20,
  memo: "ボリューム満点でお財布にもやさしい" },
{ name: "鶏むね肉のレモンクリーム煮", category: "main", genre: "洋", protein: "鶏",
  ingredients: ["鶏むね肉", "生クリームまたは牛乳", "レモン", "コンソメ"], time: 20,
  memo: "レモンの酸味でさっぱりクリーム煮" },

// --- 豚 (25品) ---
{ name: "豚の生姜焼き", category: "main", genre: "和", protein: "豚",
  ingredients: ["豚こま切れ肉", "しょうが", "しょうゆ", "みりん", "たまねぎ"], time: 15,
  memo: "定番中の定番。ご飯がすすむ甘辛だれ" },
{ name: "豚肉と野菜の回鍋肉", category: "main", genre: "中", protein: "豚",
  ingredients: ["豚バラ肉", "キャベツ", "ピーマン", "味噌", "豆板醤"], time: 15,
  memo: "ピリ辛味噌でご飯もお酒もすすむ" },
{ name: "豚バラと白菜のミルフィーユ鍋", category: "main", genre: "和", protein: "豚",
  ingredients: ["豚バラ肉", "白菜", "だし", "ポン酢"], time: 25,
  memo: "重ねて煮るだけ。野菜もたっぷり摂れる" },
{ name: "酢豚", category: "main", genre: "中", protein: "豚",
  ingredients: ["豚肉", "ピーマン", "たまねぎ", "酢", "ケチャップ", "砂糖"], time: 25,
  memo: "野菜もたっぷり、甘酢が食欲をそそる" },
{ name: "豚肉の味噌漬け焼き", category: "main", genre: "和", protein: "豚",
  ingredients: ["豚ロース肉", "味噌", "みりん", "砂糖"], time: 15,
  memo: "漬けておけば焼くだけ。冷凍もOK" },
{ name: "豚肉と大根の煮物", category: "main", genre: "和", protein: "豚",
  ingredients: ["豚バラ肉", "大根", "しょうゆ", "みりん", "だし"], time: 30,
  memo: "コトコト煮込むだけでほろほろ大根に" },
{ name: "豚しゃぶサラダ", category: "main", genre: "和", protein: "豚",
  ingredients: ["豚バラ薄切り肉", "レタス", "ポン酢", "ごまだれ"], time: 15,
  memo: "茹でるだけでさっぱりヘルシー" },
{ name: "豚肉の甘酢あんかけ", category: "main", genre: "中", protein: "豚",
  ingredients: ["豚肉", "片栗粉", "酢", "砂糖", "しょうゆ"], time: 20,
  memo: "揚げ焼きにして甘酢あんをかけるだけ" },
{ name: "豚バラともやしの蒸し焼き", category: "main", genre: "和", protein: "豚",
  ingredients: ["豚バラ肉", "もやし", "ポン酢", "ごま油"], time: 15,
  memo: "フライパン蒸しで簡単、もやしでかさ増し" },
{ name: "豚肉のしょうが焼き丼", category: "main", genre: "和", protein: "豚",
  ingredients: ["豚こま切れ肉", "しょうが", "しょうゆ", "みりん", "キャベツ"], time: 15,
  memo: "丼にすれば洗い物も少なく満足感アップ" },
{ name: "麻婆豆腐", category: "main", genre: "中", protein: "豚",
  ingredients: ["豚ひき肉", "豆腐", "豆板醤", "味噌", "しょうゆ"], time: 20,
  memo: "ピリ辛でご飯がすすむ定番中華" },
{ name: "豚肉のポークソテー", category: "main", genre: "洋", protein: "豚",
  ingredients: ["豚ロース肉", "塩", "こしょう", "小麦粉", "バター"], time: 15,
  memo: "シンプルに焼くだけ。付け合わせ自由自在" },
{ name: "豚肉の角煮風煮込み", category: "main", genre: "和", protein: "豚",
  ingredients: ["豚バラブロック肉", "しょうゆ", "みりん", "砂糖", "しょうが"], time: 30,
  memo: "圧力鍋やレンジ活用でとろとろに時短" },
{ name: "豚肉となすの味噌炒め", category: "main", genre: "和", protein: "豚",
  ingredients: ["豚こま切れ肉", "なす", "味噌", "みりん", "砂糖"], time: 15,
  memo: "なすが油と味噌をよく吸って絶品" },
{ name: "豚キムチ炒め", category: "main", genre: "中", protein: "豚",
  ingredients: ["豚バラ肉", "キムチ", "にら", "ごま油"], time: 15,
  memo: "ピリ辛でスタミナ満点、ご飯にも合う" },
{ name: "豚肉と厚揚げのオイスター炒め", category: "main", genre: "中", protein: "豚",
  ingredients: ["豚肉", "厚揚げ", "オイスターソース", "ピーマン"], time: 15,
  memo: "厚揚げでボリューム満点、コクうまおかず" },
{ name: "豚肉のカレーソテー", category: "main", genre: "洋", protein: "豚",
  ingredients: ["豚肉", "カレー粉", "小麦粉", "塩"], time: 15,
  memo: "カレー風味の下味で焼くだけの簡単おかず" },
{ name: "豚肉と白菜のクリーム煮", category: "main", genre: "洋", protein: "豚",
  ingredients: ["豚こま切れ肉", "白菜", "牛乳", "コンソメ"], time: 20,
  memo: "とろとろ白菜と豚肉のやさしい味" },
{ name: "豚肉のねぎ塩炒め", category: "main", genre: "中", protein: "豚",
  ingredients: ["豚バラ肉", "長ねぎ", "ごま油", "塩", "レモン汁"], time: 15,
  memo: "さっぱり塩だれで箸がすすむ" },
{ name: "豚肉となすのしょうが焼き", category: "main", genre: "和", protein: "豚",
  ingredients: ["豚こま切れ肉", "なす", "しょうが", "しょうゆ", "みりん"], time: 15,
  memo: "定番のしょうが焼きになすを追加してボリューム" },
{ name: "豚肉のガーリックバター醤油炒め", category: "main", genre: "和", protein: "豚",
  ingredients: ["豚肉", "にんにく", "バター", "しょうゆ"], time: 15,
  memo: "バターしょうゆの香りで食欲そそる" },
{ name: "豚肉ともやしの担々風炒め", category: "main", genre: "中", protein: "豚",
  ingredients: ["豚ひき肉", "もやし", "豆板醤", "味噌", "ごま"], time: 15,
  memo: "ピリ辛ごまだれでスタミナつく味" },
{ name: "豚バラ大根のとろとろ煮", category: "main", genre: "和", protein: "豚",
  ingredients: ["豚バラ肉", "大根", "だし", "しょうゆ", "砂糖"], time: 30,
  memo: "コトコト煮込んで味しみしみ" },
{ name: "豚肉のレモンステーキ", category: "main", genre: "洋", protein: "豚",
  ingredients: ["豚ロース肉", "レモン", "しょうゆ", "バター"], time: 15,
  memo: "さっぱり爽やかなソテー、夏にもおすすめ" },
{ name: "豚肉とアスパラの塩炒め", category: "main", genre: "洋", protein: "豚",
  ingredients: ["豚肉", "アスパラガス", "塩", "にんにく", "オリーブオイル"], time: 15,
  memo: "彩りよく、シャキシャキ食感が楽しい" },

// --- 牛 (10品) ---
{ name: "牛丼", category: "main", genre: "和", protein: "牛",
  ingredients: ["牛薄切り肉", "たまねぎ", "しょうゆ", "みりん", "砂糖"], time: 20,
  memo: "煮るだけで本格牛丼、ご飯にたっぷりのせて" },
{ name: "牛肉と野菜のプルコギ", category: "main", genre: "中", protein: "牛",
  ingredients: ["牛薄切り肉", "たまねぎ", "にんじん", "しょうゆ", "砂糖", "にんにく"], time: 20,
  memo: "甘辛だれで漬け込んで焼くだけの韓国風" },
{ name: "牛肉のオイスターソース炒め", category: "main", genre: "中", protein: "牛",
  ingredients: ["牛薄切り肉", "ピーマン", "オイスターソース", "にんにく"], time: 15,
  memo: "手早く炒めるだけで本格中華の味" },
{ name: "牛肉とごぼうの甘辛煮", category: "main", genre: "和", protein: "牛",
  ingredients: ["牛薄切り肉", "ごぼう", "しょうゆ", "みりん", "砂糖"], time: 20,
  memo: "ごぼうの香りと牛肉のコクが相性抜群" },
{ name: "ビーフステーキ", category: "main", genre: "洋", protein: "牛",
  ingredients: ["牛ステーキ肉", "塩", "こしょう", "にんにく", "バター"], time: 15,
  memo: "特別な日にも。焼き加減はお好みで" },
{ name: "牛肉と玉ねぎの甘辛炒め", category: "main", genre: "和", protein: "牛",
  ingredients: ["牛こま切れ肉", "たまねぎ", "しょうゆ", "みりん", "砂糖"], time: 15,
  memo: "牛丼の具のような甘辛炒め、ご飯にも合う" },
{ name: "牛肉のガリバタ醤油炒め", category: "main", genre: "和", protein: "牛",
  ingredients: ["牛薄切り肉", "にんにく", "バター", "しょうゆ"], time: 15,
  memo: "香ばしいガーリックバターで食欲アップ" },
{ name: "牛肉とじゃがいものカレー風味炒め", category: "main", genre: "洋", protein: "牛",
  ingredients: ["牛こま切れ肉", "じゃがいも", "カレー粉", "しょうゆ"], time: 20,
  memo: "カレー風味で子どもも喜ぶ味付け" },
{ name: "牛肉のすき焼き風煮", category: "main", genre: "和", protein: "牛",
  ingredients: ["牛薄切り肉", "白菜", "しらたき", "しょうゆ", "砂糖"], time: 20,
  memo: "割り下風の甘辛味でご飯がすすむ" },
{ name: "牛肉と彩り野菜のオイスター炒め", category: "main", genre: "中", protein: "牛",
  ingredients: ["牛薄切り肉", "パプリカ", "オイスターソース"], time: 15,
  memo: "見た目も華やかで食欲そそる炒め物" },

// --- 魚 (20品) ---
{ name: "鮭の塩焼き", category: "main", genre: "和", protein: "魚",
  ingredients: ["生鮭", "塩"], time: 15,
  memo: "焼くだけのシンプル定番。大根おろしを添えて" },
{ name: "鯖の味噌煮", category: "main", genre: "和", protein: "魚",
  ingredients: ["鯖", "味噌", "みりん", "砂糖", "しょうが"], time: 20,
  memo: "しっかり味でご飯がすすむ定番の煮魚" },
{ name: "ぶりの照り焼き", category: "main", genre: "和", protein: "魚",
  ingredients: ["ぶり", "しょうゆ", "みりん", "砂糖"], time: 15,
  memo: "照り照りのたれが食欲をそそる" },
{ name: "鮭のムニエル", category: "main", genre: "洋", protein: "魚",
  ingredients: ["生鮭", "小麦粉", "バター", "レモン"], time: 15,
  memo: "バター香るソテー、レモンでさっぱりと" },
{ name: "たらのホイル焼き", category: "main", genre: "和", protein: "魚",
  ingredients: ["たら", "きのこ", "バター", "しょうゆ"], time: 20,
  memo: "ホイルで包んで焼くだけ、洗い物少なめ" },
{ name: "あじの南蛮漬け", category: "main", genre: "和", protein: "魚",
  ingredients: ["あじ", "片栗粉", "酢", "しょうゆ", "砂糖", "たまねぎ"], time: 25,
  memo: "揚げ焼きして甘酢に漬けるさっぱりおかず" },
{ name: "さんまの塩焼き", category: "main", genre: "和", protein: "魚",
  ingredients: ["さんま", "塩", "大根おろし"], time: 15,
  memo: "秋の定番。グリルで焼くだけ" },
{ name: "鮭のちゃんちゃん焼き", category: "main", genre: "和", protein: "魚",
  ingredients: ["生鮭", "キャベツ", "味噌", "みりん", "バター"], time: 20,
  memo: "野菜もたっぷり摂れる北海道の郷土料理" },
{ name: "白身魚のバター醤油ソテー", category: "main", genre: "和", protein: "魚",
  ingredients: ["白身魚", "バター", "しょうゆ", "小麦粉"], time: 15,
  memo: "香ばしいバター醤油でご飯がすすむ" },
{ name: "鯛のアクアパッツァ", category: "main", genre: "洋", protein: "魚",
  ingredients: ["白身魚", "あさり", "トマト", "にんにく", "オリーブオイル"], time: 25,
  memo: "見た目も豪華な洋風魚料理、パンにも合う" },
{ name: "さばの竜田揚げ", category: "main", genre: "和", protein: "魚",
  ingredients: ["さば", "しょうゆ", "しょうが", "片栗粉"], time: 20,
  memo: "下味をつけて揚げ焼きに、お弁当にも" },
{ name: "鮭の南蛮漬け風", category: "main", genre: "和", protein: "魚",
  ingredients: ["生鮭", "片栗粉", "酢", "しょうゆ", "砂糖"], time: 20,
  memo: "揚げ焼きして甘酢だれでさっぱりと" },
{ name: "ぶり大根", category: "main", genre: "和", protein: "魚",
  ingredients: ["ぶり", "大根", "しょうゆ", "みりん", "砂糖"], time: 30,
  memo: "コトコト煮込んで味がしみしみ" },
{ name: "たらのマヨパン粉焼き", category: "main", genre: "洋", protein: "魚",
  ingredients: ["たら", "マヨネーズ", "パン粉", "粉チーズ"], time: 20,
  memo: "オーブンで焼くだけ、こんがり香ばしい" },
{ name: "鯖の塩焼き", category: "main", genre: "和", protein: "魚",
  ingredients: ["鯖", "塩", "大根おろし"], time: 15,
  memo: "シンプルに焼くだけで青魚の旨味を堪能" },
{ name: "えびとブロッコリーのガーリック炒め", category: "main", genre: "洋", protein: "魚",
  ingredients: ["えび", "ブロッコリー", "にんにく", "オリーブオイル"], time: 15,
  memo: "彩りよくパーティー感のある一皿" },
{ name: "白身魚の中華あんかけ", category: "main", genre: "中", protein: "魚",
  ingredients: ["白身魚", "片栗粉", "しょうゆ", "酢", "野菜あん"], time: 20,
  memo: "揚げ焼きした魚にとろみあんをかけて" },
{ name: "鮭の味噌マヨ焼き", category: "main", genre: "和", protein: "魚",
  ingredients: ["生鮭", "味噌", "マヨネーズ"], time: 15,
  memo: "混ぜて塗って焼くだけ、コクのある味" },
{ name: "いわしの梅煮", category: "main", genre: "和", protein: "魚",
  ingredients: ["いわし", "梅干し", "しょうゆ", "みりん", "しょうが"], time: 20,
  memo: "梅の酸味でいわしの臭みも気にならない" },
{ name: "たらちりウォーターソテー", category: "main", genre: "洋", protein: "魚",
  ingredients: ["たら", "白ワインまたは酒", "バター", "レモン"], time: 15,
  memo: "蒸し焼きでふっくら、あっさりヘルシー" },

// --- 卵・豆腐 (20品) ---
{ name: "麻婆豆腐(ひき肉なし)", category: "main", genre: "中", protein: "卵・豆腐",
  ingredients: ["豆腐", "豆板醤", "味噌", "しょうゆ", "ねぎ"], time: 15,
  memo: "豆腐だけでも本格的な味わい、経済的おかず" },
{ name: "厚揚げのねぎ塩炒め", category: "main", genre: "中", protein: "卵・豆腐",
  ingredients: ["厚揚げ", "長ねぎ", "ごま油", "塩"], time: 15,
  memo: "香ばしい厚揚げと塩だれの組み合わせ" },
{ name: "卵とじ丼", category: "main", genre: "和", protein: "卵・豆腐",
  ingredients: ["卵", "たまねぎ", "だし", "しょうゆ", "みりん"], time: 15,
  memo: "冷蔵庫にあるもので手早く作れる丼" },
{ name: "豆腐ステーキ", category: "main", genre: "和", protein: "卵・豆腐",
  ingredients: ["木綿豆腐", "片栗粉", "しょうゆ", "みりん", "バター"], time: 15,
  memo: "外はカリッと中はふわふわ、和風あんで" },
{ name: "オムレツ", category: "main", genre: "洋", protein: "卵・豆腐",
  ingredients: ["卵", "牛乳", "バター", "塩"], time: 10,
  memo: "手早くできる万能おかず、中身はお好みで" },
{ name: "厚揚げと野菜の中華炒め", category: "main", genre: "中", protein: "卵・豆腐",
  ingredients: ["厚揚げ", "ピーマン", "たまねぎ", "オイスターソース"], time: 15,
  memo: "野菜も摂れる満足感のある炒め物" },
{ name: "豆腐と卵のふわとろ丼", category: "main", genre: "和", protein: "卵・豆腐",
  ingredients: ["豆腐", "卵", "だし", "しょうゆ", "みりん"], time: 15,
  memo: "疲れた日でも作りやすいやさしい味" },
{ name: "厚揚げの照り焼き", category: "main", genre: "和", protein: "卵・豆腐",
  ingredients: ["厚揚げ", "しょうゆ", "みりん", "砂糖"], time: 15,
  memo: "甘辛だれが厚揚げにしっかり絡む" },
{ name: "豆腐チャンプルー", category: "main", genre: "和", protein: "卵・豆腐",
  ingredients: ["木綿豆腐", "卵", "もやし", "にら", "しょうゆ"], time: 15,
  memo: "沖縄風の炒め物、野菜もたっぷり" },
{ name: "茶碗蒸し風あんかけ豆腐", category: "main", genre: "和", protein: "卵・豆腐",
  ingredients: ["豆腐", "卵", "だし", "片栗粉"], time: 20,
  memo: "レンジで作れるやさしい味のあんかけ" },
{ name: "厚揚げの野菜あんかけ", category: "main", genre: "和", protein: "卵・豆腐",
  ingredients: ["厚揚げ", "にんじん", "しいたけ", "だし", "しょうゆ", "片栗粉"], time: 20,
  memo: "とろみあんで冷めにくく、体もあたたまる" },
{ name: "スクランブルエッグとベーコン", category: "main", genre: "洋", protein: "卵・豆腐",
  ingredients: ["卵", "ベーコン", "牛乳", "バター"], time: 10,
  memo: "朝食にも夜にも合う手早い一品" },
{ name: "豆腐と挽き肉なしそぼろ丼", category: "main", genre: "和", protein: "卵・豆腐",
  ingredients: ["豆腐", "しょうゆ", "みりん", "砂糖", "しょうが"], time: 15,
  memo: "崩した豆腐を炒り煮にしてそぼろ風に" },
{ name: "厚揚げのキムチ炒め", category: "main", genre: "中", protein: "卵・豆腐",
  ingredients: ["厚揚げ", "キムチ", "にら", "ごま油"], time: 15,
  memo: "ピリ辛キムチと厚揚げでご飯がすすむ" },
{ name: "だし巻き卵", category: "main", genre: "和", protein: "卵・豆腐",
  ingredients: ["卵", "だし", "しょうゆ", "みりん"], time: 15,
  memo: "ふんわりジューシー、大根おろしを添えて" },
{ name: "豆腐グラタン", category: "main", genre: "洋", protein: "卵・豆腐",
  ingredients: ["豆腐", "牛乳", "チーズ", "コンソメ"], time: 25,
  memo: "ヘルシーなのにコクたっぷり、あたたまる" },
{ name: "厚揚げとトマトのチーズ焼き", category: "main", genre: "洋", protein: "卵・豆腐",
  ingredients: ["厚揚げ", "トマト", "チーズ", "オリーブオイル"], time: 15,
  memo: "トースターで焼くだけの簡単イタリアン風" },
{ name: "卵とにらの中華炒め", category: "main", genre: "中", protein: "卵・豆腐",
  ingredients: ["卵", "にら", "オイスターソース", "ごま油"], time: 10,
  memo: "スピード満点、彩りもよい炒め物" },
{ name: "豆腐ハンバーグ", category: "main", genre: "洋", protein: "卵・豆腐",
  ingredients: ["木綿豆腐", "片栗粉", "たまねぎ", "ケチャップ"], time: 20,
  memo: "ふわふわ食感でヘルシー、ソースはお好みで" },
{ name: "厚揚げの甘辛煮", category: "main", genre: "和", protein: "卵・豆腐",
  ingredients: ["厚揚げ", "しょうゆ", "みりん", "砂糖", "だし"], time: 15,
  memo: "煮汁がしみて冷めても美味しい" },

// ==================== 副菜(side) 約60品 ====================

{ name: "ほうれん草のおひたし", category: "side", genre: "和",
  ingredients: ["ほうれん草", "だし", "しょうゆ", "かつお節"], time: 10,
  memo: "茹でて和えるだけの定番副菜" },
{ name: "きゅうりの浅漬け", category: "side", genre: "和",
  ingredients: ["きゅうり", "塩", "昆布"], time: 5,
  memo: "切って塩もみするだけ、あと1品ほしい時に" },
{ name: "ひじきの煮物", category: "side", genre: "和",
  ingredients: ["ひじき", "にんじん", "油揚げ", "しょうゆ", "みりん"], time: 20,
  memo: "作り置きにも便利な定番の和惣菜" },
{ name: "きんぴらごぼう", category: "side", genre: "和",
  ingredients: ["ごぼう", "にんじん", "しょうゆ", "みりん", "ごま油"], time: 15,
  memo: "シャキシャキ食感が楽しい常備菜" },
{ name: "もやしのナムル", category: "side", genre: "中",
  ingredients: ["もやし", "ごま油", "しょうゆ", "ごま"], time: 10,
  memo: "レンジで茹でて和えるだけ、簡単韓国風" },
{ name: "冷奴", category: "side", genre: "和",
  ingredients: ["豆腐", "ねぎ", "しょうゆ", "かつお節"], time: 5,
  memo: "切るだけで完成、夏に嬉しい一品" },
{ name: "小松菜の煮浸し", category: "side", genre: "和",
  ingredients: ["小松菜", "油揚げ", "だし", "しょうゆ"], time: 15,
  memo: "だしがしみて優しい味わい" },
{ name: "切り干し大根の煮物", category: "side", genre: "和",
  ingredients: ["切り干し大根", "にんじん", "油揚げ", "しょうゆ", "みりん"], time: 20,
  memo: "戻して煮るだけ、栄養満点の乾物おかず" },
{ name: "にんじんしりしり", category: "side", genre: "和",
  ingredients: ["にんじん", "卵", "ツナ缶", "しょうゆ"], time: 15,
  memo: "沖縄の定番惣菜、彩りもきれい" },
{ name: "ポテトサラダ", category: "side", genre: "洋",
  ingredients: ["じゃがいも", "きゅうり", "ハム", "マヨネーズ"], time: 20,
  memo: "定番の洋風サラダ、作り置きにも" },
{ name: "コールスローサラダ", category: "side", genre: "洋",
  ingredients: ["キャベツ", "にんじん", "マヨネーズ", "酢"], time: 10,
  memo: "千切りして和えるだけのさっぱりサラダ" },
{ name: "なすの揚げ浸し", category: "side", genre: "和",
  ingredients: ["なす", "だし", "しょうゆ", "みりん"], time: 15,
  memo: "揚げ焼きしただしに浸すだけ、冷やしても◎" },
{ name: "ブロッコリーのおかか和え", category: "side", genre: "和",
  ingredients: ["ブロッコリー", "かつお節", "しょうゆ"], time: 10,
  memo: "茹でて和えるだけ、彩りも栄養もプラス" },
{ name: "かぼちゃの煮物", category: "side", genre: "和",
  ingredients: ["かぼちゃ", "だし", "しょうゆ", "みりん", "砂糖"], time: 20,
  memo: "ほくほく甘い定番の和惣菜" },
{ name: "トマトとチーズのカプレーゼ風", category: "side", genre: "洋",
  ingredients: ["トマト", "チーズ", "オリーブオイル", "塩"], time: 5,
  memo: "切って盛るだけの華やか副菜" },
{ name: "無限ピーマン", category: "side", genre: "和",
  ingredients: ["ピーマン", "ツナ缶", "ごま油", "しょうゆ"], time: 10,
  memo: "レンジで作れる大人気の副菜" },
{ name: "白菜の浅漬け", category: "side", genre: "和",
  ingredients: ["白菜", "塩", "昆布", "唐辛子"], time: 10,
  memo: "冬に嬉しいさっぱり漬物" },
{ name: "アスパラのベーコン巻き", category: "side", genre: "洋",
  ingredients: ["アスパラガス", "ベーコン", "塩", "こしょう"], time: 15,
  memo: "巻いて焼くだけで見栄えのする一品" },
{ name: "ナムル盛り合わせ", category: "side", genre: "中",
  ingredients: ["ほうれん草", "にんじん", "もやし", "ごま油"], time: 15,
  memo: "3種の野菜をそれぞれナムルに、彩り豊か" },
{ name: "きゅうりとわかめの酢の物", category: "side", genre: "和",
  ingredients: ["きゅうり", "わかめ", "酢", "砂糖", "しょうゆ"], time: 10,
  memo: "さっぱりして箸休めにぴったり" },
{ name: "れんこんのきんぴら", category: "side", genre: "和",
  ingredients: ["れんこん", "しょうゆ", "みりん", "ごま油"], time: 15,
  memo: "シャキシャキ食感が楽しい根菜おかず" },
{ name: "大根サラダ", category: "side", genre: "和",
  ingredients: ["大根", "水菜", "ポン酢", "かつお節"], time: 10,
  memo: "せん切り大根のさっぱりサラダ" },
{ name: "アボカドとトマトのサラダ", category: "side", genre: "洋",
  ingredients: ["アボカド", "トマト", "オリーブオイル", "塩"], time: 10,
  memo: "切って和えるだけ、栄養価も高い" },
{ name: "オクラの和え物", category: "side", genre: "和",
  ingredients: ["オクラ", "かつお節", "しょうゆ"], time: 10,
  memo: "茹でて刻んで和えるだけの簡単副菜" },
{ name: "厚揚げの南蛮漬け風", category: "side", genre: "和",
  ingredients: ["厚揚げ", "たまねぎ", "酢", "しょうゆ", "砂糖"], time: 15,
  memo: "揚げ焼きした厚揚げを甘酢に漬けて" },
{ name: "キャベツの塩昆布和え", category: "side", genre: "和",
  ingredients: ["キャベツ", "塩昆布", "ごま油"], time: 5,
  memo: "混ぜるだけの超スピード副菜" },
{ name: "野菜のマリネ", category: "side", genre: "洋",
  ingredients: ["パプリカ", "きゅうり", "酢", "オリーブオイル", "砂糖"], time: 15,
  memo: "作り置きにも便利、彩りもきれい" },
{ name: "もやしと卵のスープ炒め", category: "side", genre: "中",
  ingredients: ["もやし", "卵", "鶏がらスープの素"], time: 10,
  memo: "手早くできてボリュームもある副菜" },
{ name: "ズッキーニのソテー", category: "side", genre: "洋",
  ingredients: ["ズッキーニ", "オリーブオイル", "にんにく", "塩"], time: 10,
  memo: "シンプルに焼くだけ、夏野菜を楽しむ一品" },
{ name: "春雨サラダ", category: "side", genre: "中",
  ingredients: ["春雨", "きゅうり", "ハム", "酢", "しょうゆ"], time: 15,
  memo: "つるつる食感でさっぱり食べられる" },
{ name: "たたききゅうりの中華和え", category: "side", genre: "中",
  ingredients: ["きゅうり", "ごま油", "しょうゆ", "にんにく"], time: 10,
  memo: "叩いて味を染み込ませる簡単中華副菜" },
{ name: "にんじんのグラッセ", category: "side", genre: "洋",
  ingredients: ["にんじん", "バター", "砂糖", "コンソメ"], time: 15,
  memo: "彩りのアクセントになる甘い付け合わせ" },
{ name: "白菜のクリーム煮", category: "side", genre: "洋",
  ingredients: ["白菜", "牛乳", "コンソメ", "バター"], time: 15,
  memo: "とろとろの白菜が体をあたためる" },
{ name: "ゴーヤチャンプルー風副菜", category: "side", genre: "和",
  ingredients: ["ゴーヤ", "卵", "かつお節", "しょうゆ"], time: 15,
  memo: "夏バテ防止に嬉しい沖縄野菜の副菜" },
{ name: "水菜と油揚げのさっと煮", category: "side", genre: "和",
  ingredients: ["水菜", "油揚げ", "だし", "しょうゆ"], time: 10,
  memo: "さっと煮るだけの手軽な副菜" },
{ name: "長芋の梅和え", category: "side", genre: "和",
  ingredients: ["長芋", "梅干し", "しょうゆ"], time: 10,
  memo: "叩いて和えるだけ、さっぱりネバネバ副菜" },
{ name: "ラタトゥイユ", category: "side", genre: "洋",
  ingredients: ["なす", "ズッキーニ", "トマト缶", "にんにく", "オリーブオイル"], time: 25,
  memo: "煮込むだけの南仏野菜料理、作り置き向き" },
{ name: "もやしとにらのナムル", category: "side", genre: "中",
  ingredients: ["もやし", "にら", "ごま油", "しょうゆ"], time: 10,
  memo: "レンジ加熱で簡単、彩りも良い" },
{ name: "ごぼうサラダ", category: "side", genre: "洋",
  ingredients: ["ごぼう", "にんじん", "マヨネーズ", "ごま"], time: 20,
  memo: "ごぼうの香りとマヨネーズのコクが好相性" },
{ name: "きのこのバターソテー", category: "side", genre: "洋",
  ingredients: ["しめじ", "エリンギ", "バター", "しょうゆ"], time: 10,
  memo: "きのこの旨味とバター醤油の香りが絶品" },
{ name: "白菜と塩昆布の即席漬け", category: "side", genre: "和",
  ingredients: ["白菜", "塩昆布", "ごま油"], time: 5,
  memo: "もう1品ほしい時にすぐ作れる" },
{ name: "枝豆の塩茹で", category: "side", genre: "和",
  ingredients: ["枝豆", "塩"], time: 10,
  memo: "茹でるだけ、おつまみにも副菜にもなる" },
{ name: "トマトの中華風マリネ", category: "side", genre: "中",
  ingredients: ["トマト", "ごま油", "しょうゆ", "砂糖"], time: 10,
  memo: "冷やして食べるさっぱり副菜" },
{ name: "かぶの浅漬け", category: "side", genre: "和",
  ingredients: ["かぶ", "塩", "昆布"], time: 10,
  memo: "かぶの葉も一緒に使える手軽な漬物" },
{ name: "モロヘイヤのおひたし", category: "side", genre: "和",
  ingredients: ["モロヘイヤ", "だし", "しょうゆ", "かつお節"], time: 10,
  memo: "ネバネバ食感で栄養価も高い夏野菜" },
{ name: "セロリの浅漬け", category: "side", genre: "和",
  ingredients: ["セロリ", "塩", "昆布茶"], time: 10,
  memo: "さっぱりして箸休めにぴったり" },
{ name: "キャロットラペ", category: "side", genre: "洋",
  ingredients: ["にんじん", "酢", "オリーブオイル", "砂糖"], time: 10,
  memo: "せん切りにんじんのフランス風マリネ" },
{ name: "大根の煮物", category: "side", genre: "和",
  ingredients: ["大根", "だし", "しょうゆ", "みりん"], time: 30,
  memo: "コトコト煮込んで味しみしみのやさしい一品" },
{ name: "パプリカの焼きマリネ", category: "side", genre: "洋",
  ingredients: ["パプリカ", "オリーブオイル", "酢", "にんにく"], time: 15,
  memo: "焼いて漬けるだけ、彩り鮮やかな副菜" },
{ name: "白菜と豚しゃぶの重ね蒸し(副菜サイズ)", category: "side", genre: "和",
  ingredients: ["白菜", "ポン酢", "ごまだれ"], time: 15,
  memo: "小さめの副菜としても活躍する蒸し野菜" },
{ name: "たけのこの土佐煮", category: "side", genre: "和",
  ingredients: ["たけのこ", "だし", "しょうゆ", "かつお節"], time: 20,
  memo: "春を感じるシャキシャキの煮物" },
{ name: "きゅうりの中華風漬け", category: "side", genre: "中",
  ingredients: ["きゅうり", "しょうゆ", "酢", "ごま油", "にんにく"], time: 10,
  memo: "パンチのある味付けでご飯にも合う" },
{ name: "しめじとほうれん草のソテー", category: "side", genre: "洋",
  ingredients: ["しめじ", "ほうれん草", "バター", "にんにく"], time: 10,
  memo: "手早くできる彩りの良い炒め副菜" },
{ name: "長ねぎの塩昆布和え", category: "side", genre: "和",
  ingredients: ["長ねぎ", "塩昆布", "ごま油"], time: 5,
  memo: "混ぜるだけの簡単箸休め" },
{ name: "白菜と厚揚げのさっと煮", category: "side", genre: "和",
  ingredients: ["白菜", "厚揚げ", "だし", "しょうゆ"], time: 15,
  memo: "小鉢としてもう1品欲しいときに" },
{ name: "小松菜のツナ炒め", category: "side", genre: "和",
  ingredients: ["小松菜", "ツナ缶", "しょうゆ"], time: 10,
  memo: "ツナの旨味で野菜がすすむ簡単炒め" },
{ name: "パプリカとツナのサラダ", category: "side", genre: "洋",
  ingredients: ["パプリカ", "ツナ缶", "マヨネーズ"], time: 10,
  memo: "彩り鮮やかで食卓が華やぐサラダ" },
{ name: "ブロッコリーのごまマヨ和え", category: "side", genre: "和",
  ingredients: ["ブロッコリー", "マヨネーズ", "すりごま"], time: 10,
  memo: "子どもも食べやすいまろやかな味" },
{ name: "みょうがと大葉の浅漬け", category: "side", genre: "和",
  ingredients: ["みょうが", "大葉", "塩", "酢"], time: 10,
  memo: "香味野菜で食欲がない日にもさっぱり" },
{ name: "キャベツと油揚げの煮浸し", category: "side", genre: "和",
  ingredients: ["キャベツ", "油揚げ", "だし", "しょうゆ"], time: 15,
  memo: "キャベツをたっぷり消費できる副菜" },

// ==================== 汁物(soup) 約40品 ====================

{ name: "豆腐とわかめの味噌汁", category: "soup", genre: "和",
  ingredients: ["豆腐", "わかめ", "味噌", "だし"], time: 10,
  memo: "毎日でも飽きない定番の味噌汁" },
{ name: "大根と油揚げの味噌汁", category: "soup", genre: "和",
  ingredients: ["大根", "油揚げ", "味噌", "だし"], time: 15,
  memo: "大根の甘みが染み出るやさしい味噌汁" },
{ name: "なめこの味噌汁", category: "soup", genre: "和",
  ingredients: ["なめこ", "豆腐", "味噌", "だし"], time: 10,
  memo: "とろみが心地よいさっと作れる味噌汁" },
{ name: "じゃがいもと玉ねぎの味噌汁", category: "soup", genre: "和",
  ingredients: ["じゃがいも", "たまねぎ", "味噌", "だし"], time: 15,
  memo: "ほくほく食感で満足感のある味噌汁" },
{ name: "キャベツと油揚げの味噌汁", category: "soup", genre: "和",
  ingredients: ["キャベツ", "油揚げ", "味噌", "だし"], time: 10,
  memo: "キャベツの甘みが引き立つ優しい味噌汁" },
{ name: "なすとみょうがの味噌汁", category: "soup", genre: "和",
  ingredients: ["なす", "みょうが", "味噌", "だし"], time: 10,
  memo: "夏にうれしい香り豊かな味噌汁" },
{ name: "白菜と豚肉の味噌汁", category: "soup", genre: "和",
  ingredients: ["白菜", "豚バラ肉", "味噌", "だし"], time: 15,
  memo: "具沢山で汁物だけでも満足感あり" },
{ name: "しじみの味噌汁", category: "soup", genre: "和",
  ingredients: ["しじみ", "味噌", "だし"], time: 15,
  memo: "旨味たっぷり、肝臓にもやさしいと言われる汁" },
{ name: "小松菜と油揚げの味噌汁", category: "soup", genre: "和",
  ingredients: ["小松菜", "油揚げ", "味噌", "だし"], time: 10,
  memo: "手早く作れる栄養バランスの良い味噌汁" },
{ name: "ほうれん草としめじの味噌汁", category: "soup", genre: "和",
  ingredients: ["ほうれん草", "しめじ", "味噌", "だし"], time: 10,
  memo: "きのこの旨味がしみた味噌汁" },
{ name: "豚汁", category: "soup", genre: "和",
  ingredients: ["豚バラ肉", "大根", "にんじん", "ごぼう", "味噌", "だし"], time: 25,
  memo: "具沢山でこれだけでもおかずになる一品" },
{ name: "けんちん汁", category: "soup", genre: "和",
  ingredients: ["大根", "にんじん", "豆腐", "ごぼう", "しょうゆ", "だし"], time: 25,
  memo: "根菜たっぷりの精進風汁物" },
{ name: "かき玉汁", category: "soup", genre: "和",
  ingredients: ["卵", "だし", "しょうゆ", "片栗粉"], time: 10,
  memo: "ふわふわ卵が優しい味わいのすまし汁" },
{ name: "あさりの潮汁", category: "soup", genre: "和",
  ingredients: ["あさり", "昆布だし", "塩", "酒"], time: 15,
  memo: "あさりの旨味がしみ出すシンプルな汁" },
{ name: "とろろ昆布の即席汁", category: "soup", genre: "和",
  ingredients: ["とろろ昆布", "しょうゆ", "お湯"], time: 5,
  memo: "お湯を注ぐだけの超簡単な汁物" },
{ name: "たまねぎと卵のかきたま汁", category: "soup", genre: "和",
  ingredients: ["たまねぎ", "卵", "だし", "しょうゆ"], time: 10,
  memo: "たまねぎの甘みとふわふわ卵の組み合わせ" },
{ name: "きのこと豆腐のすまし汁", category: "soup", genre: "和",
  ingredients: ["しめじ", "豆腐", "だし", "しょうゆ"], time: 10,
  memo: "あっさりとした和風の澄まし汁" },
{ name: "白菜としいたけの味噌汁", category: "soup", genre: "和",
  ingredients: ["白菜", "しいたけ", "味噌", "だし"], time: 10,
  memo: "旨味のあるきのこと白菜の味噌汁" },
{ name: "もやしと卵の中華スープ", category: "soup", genre: "中",
  ingredients: ["もやし", "卵", "鶏がらスープの素", "ごま油"], time: 10,
  memo: "手早くできる具沢山中華スープ" },
{ name: "わかめと卵の中華スープ", category: "soup", genre: "中",
  ingredients: ["わかめ", "卵", "鶏がらスープの素"], time: 10,
  memo: "定番の中華スープ、ラー油を垂らしても" },
{ name: "豆腐と青菜の中華スープ", category: "soup", genre: "中",
  ingredients: ["豆腐", "チンゲン菜", "鶏がらスープの素", "ごま油"], time: 10,
  memo: "野菜も摂れるあっさり中華スープ" },
{ name: "コーンスープ", category: "soup", genre: "洋",
  ingredients: ["コーン缶", "牛乳", "コンソメ", "バター"], time: 15,
  memo: "ミキサーがなくてもコーン缶でとろとろに" },
{ name: "オニオンスープ", category: "soup", genre: "洋",
  ingredients: ["たまねぎ", "コンソメ", "バター"], time: 20,
  memo: "じっくり炒めた玉ねぎの甘みが決め手" },
{ name: "野菜たっぷりミネストローネ", category: "soup", genre: "洋",
  ingredients: ["トマト缶", "たまねぎ", "にんじん", "セロリ", "コンソメ"], time: 25,
  memo: "野菜を煮込むだけの具沢山スープ" },
{ name: "クラムチャウダー", category: "soup", genre: "洋",
  ingredients: ["あさり缶", "じゃがいも", "牛乳", "コンソメ"], time: 20,
  memo: "あさり缶を使えば手軽に本格的な味に" },
{ name: "キャベツとベーコンのコンソメスープ", category: "soup", genre: "洋",
  ingredients: ["キャベツ", "ベーコン", "コンソメ"], time: 15,
  memo: "煮込むだけの優しい味の野菜スープ" },
{ name: "ポタージュ風じゃがいもスープ", category: "soup", genre: "洋",
  ingredients: ["じゃがいも", "牛乳", "コンソメ", "バター"], time: 20,
  memo: "つぶして混ぜるだけで本格ポタージュ風" },
{ name: "トマトと卵のスープ", category: "soup", genre: "中",
  ingredients: ["トマト", "卵", "鶏がらスープの素"], time: 10,
  memo: "酸味とふわふわ卵の中華風スープ" },
{ name: "春雨スープ", category: "soup", genre: "中",
  ingredients: ["春雨", "もやし", "鶏がらスープの素", "ごま油"], time: 10,
  memo: "つるつる食感でお腹も満たされるスープ" },
{ name: "きくらげと卵の中華スープ", category: "soup", genre: "中",
  ingredients: ["きくらげ", "卵", "鶏がらスープの素"], time: 10,
  memo: "コリコリ食感が楽しい中華スープ" },
{ name: "ほうれん草の中華スープ", category: "soup", genre: "中",
  ingredients: ["ほうれん草", "鶏がらスープの素", "ごま油"], time: 10,
  memo: "緑黄色野菜を手軽に摂れるスープ" },
{ name: "ふわふわ豆腐の中華スープ", category: "soup", genre: "中",
  ingredients: ["豆腐", "卵", "鶏がらスープの素", "片栗粉"], time: 10,
  memo: "とろみをつけてあたたまる優しいスープ" },
{ name: "レタスと卵のスープ", category: "soup", genre: "中",
  ingredients: ["レタス", "卵", "鶏がらスープの素"], time: 10,
  memo: "しゃきしゃきレタスがさっぱり美味しい" },
{ name: "根菜の味噌汁", category: "soup", genre: "和",
  ingredients: ["大根", "にんじん", "ごぼう", "味噌", "だし"], time: 20,
  memo: "根菜の旨味がしみ出る具沢山味噌汁" },
{ name: "豆乳味噌汁", category: "soup", genre: "和",
  ingredients: ["豆乳", "味噌", "だし", "わかめ"], time: 10,
  memo: "まろやかでコクのある変わり味噌汁" },
{ name: "冬瓜のとろとろスープ", category: "soup", genre: "和",
  ingredients: ["冬瓜", "鶏がらスープの素", "片栗粉"], time: 20,
  memo: "夏にうれしい体を冷ますとろみスープ" },
{ name: "たまねぎとベーコンの味噌汁", category: "soup", genre: "和",
  ingredients: ["たまねぎ", "ベーコン", "味噌", "だし"], time: 15,
  memo: "洋風食材を使った変わり味噌汁" },
{ name: "かぼちゃの味噌汁", category: "soup", genre: "和",
  ingredients: ["かぼちゃ", "味噌", "だし"], time: 15,
  memo: "かぼちゃの甘みがほっとする味噌汁" },
{ name: "しめじとわかめのすまし汁", category: "soup", genre: "和",
  ingredients: ["しめじ", "わかめ", "だし", "しょうゆ"], time: 10,
  memo: "あっさりとした優しいすまし汁" },
{ name: "豚肉と野菜の中華スープ", category: "soup", genre: "中",
  ingredients: ["豚肉", "白菜", "鶏がらスープの素"], time: 15,
  memo: "具沢山でおかずにもなるボリュームスープ" },

];

// ユーティリティ: カテゴリ別に取得
function getRecipesByCategory(category) {
  return RECIPES.filter(r => r.category === category);
}
